#!/bin/sh
#
# Author:           Marin Atanasov Nikolov <dnaeon@gmail.com>
#
### BEGIN INIT INFO
# Provides:          service-mgrd
# Required-Start:    
# Required-Stop:
# X-Start-Before:    
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6 
# Short-Description: Service Manager daemon
### END INIT INFO
 
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
DESC="service-mgrd daemon"
NAME=service-mgrd
LOGFILE="/var/log/service-mgr/service-mgrd.log"
DAEMON=/usr/local/bin/service-mgrd
SCRIPTNAME=/etc/init.d/"$NAME"
MGMT_INTERFACE="tcp://localhost:5800"

set -e
 
# /etc/init.d/service-mgrd: start and stop the Service Manager daemon

. /etc/rc.d/init.d/functions

[ -f /etc/sysconfig/service-mgrd ] && . /etc/sysconfig/service-mgrd
 
do_start() {
    ${DAEMON} -d -o ${LOGFILE} start
}

do_stop() {
    ${DAEMON} -e ${MGMT_INTERFACE} stop
}
 
do_status() {
    ${DAEMON} -e ${MGMT_INTERFACE} status
}
 
case "${1}" in
    start)
        do_start
        ;;
    reset|stop)
        do_stop
        ;;
    status)
        do_status
        ;;
    reload|restart|force-reload)
        do_stop
        do_start
        ;;
    *)
        log_success_msg "usage: ${0} {start|stop|status|reload|restart|force-reload|reset}" >&2
        ;;
esac
